peidashboard/peidashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from dashboard import views

#from django.views.generic import RedirectView
from django.urls import include, path
from rest_framework import routers

#from rest_framework.urlpatterns import format_suffix_patterns

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
#router.register(r'snippets', views.SnippetViewSet)
#router.register(r'users', views.UserViewSet)
router.register(r'folders', views.FolderViewSet)
router.register(r'ytlinks', views.YTLinkViewSet)
router.register(r'documents', views.DocumentViewSet)
router.register(r'crops', views.CropViewSet)
router.register(r'agentupdates', views.AgentUpdateViewSet)
router.register(r'agent', views.AgentViewSet)
router.register(r'agentgroups', views.AgentGroupViewSet)
router.register(r'spaces', views.SpaceViewSet)
router.register(r'people', views.PersonViewSet)
router.register(r'stats', views.StatsViewSet)
router.register(r'contentprograms', views.ContentProgramViewSet)
router.register(r'programentries', views.ProgramEntryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='index'),
    
    path('api-auth/', include('rest_framework.urls'), name='api-auth'),

    path('api/', include(router.urls), name='api'),

    path('download/<slug>', views.file_view, name='file_view'), # Downloads file
    path('qr/<slug>', views.qr_view, name='qr_view'), # Downloads .png
    path('view/<slug>', views.viewfile_view, name='viewfile_view'), # Views file

    path('control/<hash>', views.control_view, name='control_view'),

    path('spaces/', views.space_view, name='space_view'),
    path('spaces/addgroup/<int:space>', views.space_create_group, name='space_create_group'),
    #path('spaces/<int:id>', views.space_individual, name='space_individual'),

    #path('groups/', views.group_view, name='group_view'),
    path('groups/<int:id>', views.group_individual, name='group_individual'),

    path('agents/', views.agent_view, name='agent_view'),
    #path('agents/<int:id>', views.agent_individual, name='agent_individual'),

    path('documents/<int:id>', views.document_individual, name='document_individual'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

peidashboard/dashboard/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE, SET_NULL

# from pygments.lexers import get_all_lexers
# from pygments.styles import get_all_styles

# from pygments.lexers import get_lexer_by_name
# from pygments.formatters.html import HtmlFormatter
# from pygments import highlight

from django.conf import settings

import os

from datetime import datetime

import time

from jsonfield import JSONField

from django.utils.timezone import now

import hashlib

import qrcode

from PyPDF2 import PdfFileWriter, PdfFileReader

import urllib.request
import json
import urllib
import pprint

import pafy

from django.utils.functional import keep_lazy_text

class Folder(models.Model):
    parentdir = models.ForeignKey("Folder", on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['name']

class YTLink(models.Model):
    parentdir = models.ForeignKey(Folder, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    link = models.URLField(default='', unique=True)
    title = models.CharField(max_length=100, blank=True, default='')
    duration = models.PositiveIntegerField()
    # STATISTICS
    viewtime = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['title']

    def save(self, *args, **kwargs):

        link = self.link # https://www.youtube.com/watch?v=iEVdFWgx6_0&list=...&index=...
        VideoID = link.split("&")[0].split("=")[-1]
        #print(VideoID)

        video = pafy.new(link)
        print(video.duration)
        split = (""+video.duration).split(':')
        print( (int(split[0])*3600 + int(split[1])*60 + int(split[2])), "seconds")
        self.duration = int(split[0])*3600 + int(split[1])*60 + int(split[2])

        params = {"format": "json", "url": "https://www.youtube.com/watch?v=%s" % VideoID}
        url = "https://www.youtube.com/oembed"
        query_string = urllib.parse.urlencode(params)
        url = url + "?" + query_string

        with urllib.request.urlopen(url) as response:
            response_text = response.read()
            data = json.loads(response_text.decode())
            pprint.pprint(data)
            title = data['title']
            #print(title)
            self.title = title
        
        super(YTLink, self).save(*args, **kwargs)
    
    @property
    def pretty_duration(self):
        return time.strftime('%H:%M:%S', time.gmtime(self.duration))
    
    @property
    def pretty_viewtime(self):
        return time.strftime('%H:%M:%S', time.gmtime(self.viewtime))

class Document(models.Model):
    parentdir = models.ForeignKey(Folder, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    docfile = models.FileField(upload_to='media', unique=True)
    docname = models.CharField(max_length=100, blank=True, default='')
    downloadlink = models.URLField(editable=False, default='')
    viewlink = models.URLField(editable=False, default='')
    # STATISTICS
    viewtime = models.PositiveIntegerField(default=0)
    pages = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['docfile']
    
    @keep_lazy_text
    def get_valid_filename(s):
        """
        Returns the given string converted to a string that can be used for a clean
        filename. Specifically, leading and trailing spaces are removed; other
        spaces are converted to underscores; and anything that is not a unicode
        alphanumeric, dash, underscore, or dot, is removed.
        >>> get_valid_filename("john's portrait in 2004.jpg")
        'johns_portrait_in_2004.jpg'
        """
        s = force_text(s).strip().replace(' ', '_')
        return re.sub(r'(?u)[^-\w.]', '', s)

    def save(self, *args, **kwargs):

        super(Document, self).save(*args, **kwargs)
        
        #print(self.docfile.name)

        # SET A DOWNLOAD LINK (AND VIEW)
        self.downloadlink = 'http://' + \
            settings.ALLOWED_HOSTS[0]+'/download/' + \
            self.docfile.name.split('/')[-1]
        
        self.viewlink = 'http://' + \
            settings.ALLOWED_HOSTS[0]+'/view/' + \
            self.docfile.name.split('/')[-1]
        
        self.docname = self.docfile.name.split('/')[-1]

        super(Document, self).save(*args, **kwargs)

        # ONCE DOC IS SAVED, IF IT'S PDF, THEN SEPARATE
        isPDF = True
        pages = 0
        target = os.path.dirname(os.path.abspath(__file__))+'/../media_cdn/'+str(self.docfile)
        #print(target)
        try:
            inputpdf = PdfFileReader(open(target, "rb"))
            
            for i in range(inputpdf.numPages):
                output = PdfFileWriter()
                output.addPage(inputpdf.getPage(i))
                with open("%s____%04d" % (target, i+1), "wb") as outputStream:
                    output.write(outputStream)
                pages += 1
        except:
            #print("not a PDF file")
            isPDF = False

        if isPDF:
            self.pages = pages
            # SAVE AGAIN BECAUSE OF PAGES
            super(Document, self).save(*args, **kwargs)

    @property
    def pretty_viewtime(self):
        return time.strftime('%H:%M:%S', time.gmtime(self.viewtime))


class Space(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        super(Space, self).save(*args, **kwargs)
        groupname = "Grp_" + self.name
        if AgentGroup.objects.filter(name=groupname).count() == 0:
            newgroup = AgentGroup(
                name=groupname, space=Space.objects.get(pk=self.pk))
            newgroup.save()


class AgentGroup(models.Model):
    name = models.CharField(max_length=100)
    space = models.ForeignKey(Space, on_delete=models.CASCADE)

    class Meta:
        ordering = ['space', 'name']


class Agent(models.Model):
    name = models.CharField(max_length=100, unique=True)
    group = models.ForeignKey(AgentGroup, null=True, on_delete=models.SET_NULL)
    # USE agent.update TO ACCESS THE CORRESPONDING AgentUpdate INSTANCE

    class Meta:
        ordering = ['group', 'id']

    def save(self, *args, **kwargs):
        super(Agent, self).save(*args, **kwargs)
        print(AgentUpdate.objects.filter(pk=self.pk))
        print(AgentUpdate.objects.filter(pk=self.pk).count())
        if AgentUpdate.objects.filter(pk=self.pk).count() == 0:
            newhash = str(  hashlib.md5( ( str(self.pk)+str(now()) ).encode() ).hexdigest()  )
            print("newhash", newhash)
            update = AgentUpdate(
                agent=Agent.objects.get(pk=self.pk),
                url_hash=newhash,
                content_confirm=True
            )
            update.save()
        else:
            update = AgentUpdate.objects.get(pk=self.pk)
            update.content_confirm = True
            update.save()


class Person(models.Model):
    descriptor = JSONField()


class Stats(models.Model):
    person = models.ForeignKey(Person, null=True, on_delete=models.CASCADE)

    content = models.ForeignKey(Document, null=True, on_delete=models.CASCADE)
    ytcontent = models.ForeignKey(YTLink, null=True, on_delete=models.CASCADE)

    agent = models.ForeignKey(Agent, null=True, on_delete=models.CASCADE)
    attention = models.FloatField()
    neutral = models.PositiveIntegerField(default=0)
    happiness = models.PositiveIntegerField(default=0)
    surprise = models.PositiveIntegerField(default=0)
    sadness = models.PositiveIntegerField(default=0)
    anger = models.PositiveIntegerField(default=0)
    disgust = models.PositiveIntegerField(default=0)
    fear = models.PositiveIntegerField(default=0)
    contempt = models.PositiveIntegerField(default=0)
    frames = models.PositiveIntegerField(default=0)

    # 2 NULLS,  2 NAO NULLS. ESTES CASOS NAO SERVEM
    # vvvv Caso eu faça asneira nos forms vvvv
    def save(self, *args, **kwargs):
        if not (self.content == None and self.ytcontent == None) and not (self.content != None and self.ytcontent != None):
            super(Stats, self).save(*args, **kwargs)

from humanfriendly import format_timespan

# USE agent.update TO ACCESS THIS !!!!!!!!!!!
class AgentUpdate(models.Model):
    agent = models.OneToOneField(
        Agent,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='update'
    )
    url_hash = models.CharField(max_length=32, unique=True)
    expires = models.DateTimeField(null=True)
    expires_max = models.DateTimeField(
        null=True)  # given first interaction, sets this to avoid continuous "dominance"

    # When a request is made, one of the following 2 fields HAS TO BE NULL!!!!!!!!!!!!!!
    content = models.ForeignKey(Document, null=True, on_delete=models.SET_NULL)
    ytcontent = models.ForeignKey(YTLink, null=True, on_delete=models.SET_NULL)

    contentpage = models.IntegerField(default=0)
    content_confirm = models.BooleanField(default=False)

    @property
    def timesince(self): # IN SECONDS
        try:
            return ( now() - self.expires ).total_seconds()
        except:
            return None

    @property
    def pretty_timesince(self): # Y M D H m s
        ts = self.timesince
        if ts != None:
            return format_timespan(ts)
        return None


    # vvvv Caso eu faça asneira nos forms vvvv
    def save(self, *args, **kwargs):
        # 2 NULLS,  2 NAO NULLS. ESTES CASOS NAO SERVEM
        #if not (self.content == None and self.ytcontent == None) and not (self.content != None and self.ytcontent != None):
        # ________  2 NAO NULLS. ESTE_ CASO_ NAO SERVE_
        if not (self.content != None and self.ytcontent != None):
            
            if AgentUpdate.objects.filter(pk=self.pk).count() != 0:
                old = AgentUpdate.objects.get(pk=self.pk)

peidashboard/dashboard/forms.py
from rest_framework import fields
from dashboard.models import *
from django import forms
from django.forms.models import ModelForm
from django.forms import ValidationError

class FolderForm(forms.Form):
    parentdir = forms.ModelChoiceField(queryset=Folder.objects.all()) # required = True
    name = forms.CharField(label='Name', max_length=100)

    def clean(self):
        cd = self.cleaned_data

        for folder in Folder.objects.all():
            if folder.name == cd.get("name"):
                raise ValidationError({'name': ["Sorry. You can't name another folder '"+ folder.name +"'.",]})

class YTLinkForm(forms.Form):
    parentdir = forms.ModelChoiceField(queryset=Folder.objects.all())
    link = forms.URLField(empty_value='', required=False)

class UploadFileForm(forms.Form):
    parentdir = forms.ModelChoiceField(queryset=Folder.objects.all())
    docfile = forms.FileField(label='Insert file', widget=forms.ClearableFileInput(attrs={'multiple': True}))

class SpaceForm(ModelForm):
    class Meta:
        model = Space
        fields = ['name']

class AgentGroupForm(ModelForm):
    class Meta:
        model = AgentGroup
        fields = ['name', 'space']

class AgentForm(forms.Form):
    id = forms.IntegerField(min_value=0)
    name = forms.CharField(label='Name', required=True, max_length=100)
    group = forms.ModelChoiceField(queryset=AgentGroup.objects.all())

    def clean(self):
        cd = self.cleaned_data

        if Agent.objects.filter(pk=cd.get("id")).count() > 0:
            raise ValidationError("Agent with this Id already exists.")
        for agent in Agent.objects.all():
            if agent.name == cd.get("name"):
                raise ValidationError("Agent with this Name already exists.")
        
        return cd

class ProgramEntryForm(ModelForm):
    content = forms.ModelChoiceField(queryset=Document.objects.all(), required=False)
    ytcontent = forms.ModelChoiceField(queryset=YTLink.objects.all(), required=False)

    class Meta:
        model = ProgramEntry
        fields = ['program', 'content', 'ytcontent', 'duration']

class ContentProgramForm(ModelForm):
    class Meta:
        model = ContentProgram
        fields = ['group', 'name', 'start_date']

peidashboard/dashboard/templates/group_individual.html
{% extends "base_generic.html" %}

{% block content %}


<br />
<a href="/spaces">Spaces</a> > {{ group.space.name }} > {{ group.name }}
<br /><br />

<ul>
    <div class="float-left">
        <p class="h2">
            {{ group.name }}
        </p>
    </div>

    <div class="float-right">
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">Delete</button>
    </div><br>


    

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
    
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    {% if group.agent_set.all.count > 0 %}
                        <p>CAREFUL</p>
                        <p>
                            {{ group.agent_set.all.count }}
                            {% if group.agent_set.all.count == 1 %}
                                agent belongs
                            {% else %}
                                agents belong
                            {% endif %}
                            to this group. They won't be deleted but they won't be associated with any group, therefore not displaying any contents.
                        </p>
                    {% else %}
                        0 agents belong to this group. It is safe to delete.
                    {% endif %}
                </div>

                <div class="modal-footer">

                    <form action="{% url 'group_individual' group.id %}" method="POST">
                        {% csrf_token %}
                
                        <input type="hidden" name="group" value="{{ group.id }}" id="id_group">
                        <input class="btn btn-danger" name="group_delete" type="submit" value="Confirm Delete" />
                    </form>

                </div>
            </div>
    
        </div>
    </div>

    



    

    


    

</ul>

<br />
{% if group.agent_set.all.count > 0 %}
This group's agents:
<br /><br />
<ul>

    <div style="border-radius: 6px; padding: 0% 1% 0% 1%; background-color: #EEEEEE;">
        {% for agent in group.agent_set.all %}

        <p class="h6">[{{ agent.id }}] {{ agent.name }}</p>

        {% endfor %}
    </div>

</ul>

{% else %}
<p>No agents.</p>
{% endif %}

{% if group.contentprogram_set.all.count == 0 %}

<br />
New program:
<br />
<ul>
    <form action="{% url 'group_individual' group.id %}" method="POST">
        {% csrf_token %}

        <p>{{ programform.non_field_errors }}</p>

        <input type="hidden" name="group" value="{{ group.id }}" id="id_group">

        <div class="form-row">

            <div class="form-group col-md">
                <input class="form-control" placeholder="Name" type="text" name="name" maxlength="100" required=""
                    id="id_name">
            </div>
            <div class="form-group col-auto">
                <input class="form-control" type="text" name="start_date" value="{{ actualtime }}" required=""
                    id="id_start_date">
            </div>
            <div class="form-group col-auto">
                <input class="btn btn-primary" name="program_upload" type="submit" value="Submit" />
            </div>
        </div>

    </form>

</ul>

{% endif %}

<br />
{% if group.contentprogram_set.all.count > 0 %}
This group's programs:
<br /><br />
<ul>

    <div style="border-radius: 6px; padding: 2% 2% 0% 2%; background-color: #EEEEEE;">
        {% for program in group.contentprogram_set.all %}


        <form action="{% url 'group_individual' group.id %}" method="POST">
            {% csrf_token %}

            <div class="form-row">
                <div class="form-group col-md">
                    <span class="h4">{{ program.name }}</span>
                </div>
                <div class="form-group col-auto">
                    <input type="hidden" name="program" value="{{ program.id }}" id="id_program">
                    <input class="btn btn-danger" name="program_delete" type="submit" value="Delete" />
                </div>
            </div>
        </form>


        <p class="h6">Start date: {{ program.start_date }}</p>

        <br />
        <ul>

            New entry:
<!--
            <form action="{% url 'group_individual' group.id %}" method="POST">
                {% csrf_token %}
                {{ entryform.non_field_errors }}
                {{ entryform }}
                <input class="btn btn-outline-dark" name="entry_upload" type="submit" value="Submit" />
            </form>
-->
            <br />
            <ul>
                <form action="{% url 'group_individual' group.id %}" method="POST">
                    {% csrf_token %}

                    <p>{{ entryform.non_field_errors }}</p>

                    <input type="hidden" name="program" value="{{ program.id }}" id="id_program">

                    <div class="form-row">

                        <div class="form-group col-md">
                            <select class="form-control" name="content" required id="id_content">
                                <option selected="">Select a document</option>

                                {% for doc in documents %}
                                        <option value="{{ doc.id }}">{{ doc.docname }}</option>
                                {% endfor %}

                            </select>
                        </div>

                        <div class="form-group col-auto">
                            <input class="form-control" placeholder="Duration (seconds)" type="number" name="duration"
                                min="0" required id="id_duration">
                        </div>
                        <div class="form-group col-auto">
                            <input class="btn btn-primary" name="entry_upload" type="submit" value="Submit" />
                        </div>
                    </div>

                </form>
                or
                <form action="{% url 'group_individual' group.id %}" method="POST">
                    {% csrf_token %}

                    <p>{{ entryform.non_field_errors }}</p>

                    <input type="hidden" name="program" value="{{ program.id }}" id="id_program">

                    <div class="form-row">

                        <div class="form-group col-md">
                            <select class="form-control" name="ytcontent" required id="id_ytcontent">
                                <option selected="">Select a YouTube video</option>

                                {% for link in ytlinks %}
                                        <option value="{{ link.id }}">{{ link.title }} - {{ link.pretty_duration }}</option>
                                {% endfor %}

                            </select>
                        </div>

                        <input type="hidden" class="form-control" placeholder="Duration (seconds)" type="number" name="duration"
                                min="0" required id="id_duration" value="5">

                        <div class="form-group col-auto">
                            <input class="btn btn-primary" name="entry_upload" type="submit" value="Submit" />
                        </div>
                    </div>


                </form>

            </ul>

            {% if program.programentry_set.all.count > 0 %}
            Entries:
            <ul>
                <div style="border-radius: 6px; padding: 0% 1% 0% 1%; background-color: #DDDDDD;">
                    {% for entry in program.programentry_set.all %}

                    <form action="{% url 'group_individual' group.id %}" method="POST">
                        {% csrf_token %}

                        <div class="form-row">
                            <div class="form-group col-md">
                                <span class="h6">
                                    {% if entry.content %}
                                        {{ entry.content.docname }}
                                    {% elif entry.ytcontent %}
                                        {{ entry.ytcontent.title }}
                                    {% endif %}
                                     - {{ entry.duration }}s
                                </span>
                            </div>
                            <div class="form-group col-auto">
                                <input type="hidden" name="entry" value="{{ entry.id }}" id="id_entry">
                                <button name="entry_delete" type="submit" style="   background:none;
                                                                                    border:none;
                                                                                    margin:0;
                                                                                    padding:0;
                                                                                    cursor: pointer;
                                                                                    color: red;">
                                    Delete
                                </button>
                            </div>
                        </div>
                    </form>


                    {% endfor %}
                </div>
            </ul>
            {% else %}
            No entries.
            {% endif %}



        </ul>


        <br />
        {% endfor %}

    </div>

</ul>

{% else %}
<p>No programs.</p>
{% endif %}


{% endblock %}

peidashboard/dashboard/templates/space_view.html
{% extends "base_generic.html" %}

{% block content %}


<br />
New space:
<br /><br />

<ul>
    <form action="{% url 'space_view' %}" method="POST">
        {% csrf_token %}

        <p>{{ spaceform.non_field_errors }}</p>

        <div class="form-row">
            <div class="form-group col-md">
                {{ spaceform.name.errors }}
                <input class="form-control" placeholder="Name" type="text" name="name" maxlength="100" required="" id="id_name">
            </div>

            <div class="form-group col-auto">
                <input class="btn btn-primary" name="space_submit" type="submit" value="Submit" />
            </div>
        </div>

    </form>
</ul>

{% if spaces %}
All spaces in the database:
<br /><br />
<ul>

    <div style="border-radius: 10px; padding: 0% 2% 3% 2%; background-color: #FFFFFF;">
        {% for space in spaces %}

            <div style="padding: 3% 0% 0% 0%;" >
                
                <span class="h4">
                    
                        {{ space.name }}
                        <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            New Group
                        </button>
                        <div class="dropdown-menu">
                            <form action="{% url 'space_create_group' space=space.id %}" method="POST" class="px-4 py-1">
                                {% csrf_token %}
                                <p>New group</p>
                                <p>{{ groupform.non_field_errors }}</p>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Name" type="text" name="name" maxlength="100"
                                        required="" id="id_name">
                                    <input type="hidden" name="space" required="" value="{{ space.id }}" id="id_space">
                                </div>
                                <input class="btn btn-sm btn-primary" name="group_submit" type="submit" value="Submit" />
                            </form>
                        </div>
                </span>

                <div class="float-right">
                    <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#myModal{{ space.id }}">Delete</button>
                </div><br>
            
                <!-- Modal -->
                <div id="myModal{{ space.id }}" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                                {% if space.agentgroup_set.all.count > 0 %}
                                    <p>CAREFUL</p>
                                    <p>
                                        {{ space.agentgroup_set.all.count }}
                                        {% if space.agentgroup_set.all.count == 1 %}
                                            group belongs
                                        {% else %}
                                            groups belong
                                        {% endif %}
                                        to this space. Their agents won't be deleted but they won't be associated with any group, therefore not displaying any contents.
                                    </p>
                                {% else %}
                                    0 groups belong to this space. It is safe to delete.
                                {% endif %}
                            </div>
            
                            <div class="modal-footer">
            
                                <form action="{% url 'space_view' %}" method="POST">
                                    {% csrf_token %}
                                    
                                    <input type="hidden" name="space" value="{{ space.id }}" id="id_space">
                                    <input class="btn btn-danger" name="space_delete" type="submit" value="Delete" />
                                    
                                </form>
            
                            </div>
                        </div>
                
                    </div>
                </div>

            </div>

            
            {% if space.agentgroup_set.all.count != 0 %}
            <div style="border-radius: 8px; margin-top: 2%; margin-left: 2%; padding: 1%; background-color: #EEEEEE;">
                {% for group in space.agentgroup_set.all %}

                    <p class="h5"><a href="/groups/{{group.id}}">{{ group.name }}</a></p>

                    <div style="border-radius: 6px; margin-left: 5%; padding: 0% 1% 0% 1%; background-color: #DDDDDD;">
                        {% for agent in group.agent_set.all %}

                        <p class="h6">[{{ agent.id }}] {{ agent.name }}</p>

                        {% endfor %}
                    </div>

                    {% endfor %}
            </div>
            {% endif %}

            
        
        {% endfor %}
    </div>

</ul>

{% else %}
<p>No spaces.</p>
{% endif %}




{% endblock %}